SHOW TRANSACTION ISOLATION LEVEL;

-- In PSQL, we can only set tx isolation level while starting a tx
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
-- In PSQL READ UNCOMMITTED behaves like READ COMMITTED, basically PSQL has 3 isolation levels

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;