-- Queries to SET TX Levels in MySQL
SET SESSION TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED;
SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;
SET SESSION TRANSACTION ISOLATION LEVEL SERIALIZABLE;
SELECT @transaction_isolaiton;

-- CMDs to start tx:
BEGIN;
START TRANSACTION;
-- COMMIT:
COMMIT;